/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tr1nks_MyNative */

#ifndef _Included_com_tr1nks_MyNative
#define _Included_com_tr1nks_MyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tr1nks_MyNative
 * Method:    voidMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tr1nks_MyNative_voidMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_tr1nks_MyNative
 * Method:    staticVoidMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tr1nks_MyNative_staticVoidMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_tr1nks_MyNative
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tr1nks_MyNative_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tr1nks_MyNative
 * Method:    staticIntMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tr1nks_MyNative_staticIntMethod
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tr1nks_MyNative
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tr1nks_MyNative_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tr1nks_MyNative
 * Method:    staticStringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tr1nks_MyNative_staticStringMethod
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_tr1nks_MyNative
 * Method:    intArrayMethod
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tr1nks_MyNative_intArrayMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_tr1nks_MyNative
 * Method:    staticIntArrayMethod
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tr1nks_MyNative_staticIntArrayMethod
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_tr1nks_MyNative
 * Method:    stringArrayMethod
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tr1nks_MyNative_stringArrayMethod
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_tr1nks_MyNative
 * Method:    staticStringArrayMethod
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tr1nks_MyNative_staticStringArrayMethod
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
